# Generated by Django 4.0.5 on 2022-09-29 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('ApePaterno', models.CharField(max_length=25)),
                ('ApeMaterno', models.CharField(max_length=25)),
                ('Edad', models.IntegerField()),
                ('Email', models.EmailField(max_length=255)),
                ('Direccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomCompleto', models.CharField(max_length=100)),
                ('Cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Piso', models.IntegerField()),
                ('Numero', models.IntegerField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('enUso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descripcion', models.TextField()),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Eliminado', 'Eliminado')], max_length=12)),
                ('DiasEstadia', models.IntegerField()),
                ('FechaIngreso', models.DateTimeField()),
                ('FechaSalida', models.DateTimeField()),
                ('Monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('MetodoPago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta')], max_length=10)),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservasApp.cliente')),
                ('Empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservasApp.empleado')),
                ('Habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservasApp.habitacion')),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('TotalGasto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservasApp.reserva')),
                ('Servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReservasApp.servicio')),
            ],
        ),
    ]
